### ISSUE TITLE
Module parse failed: Unexpected token (85:10)

### ISSUE THREAD

**Issue by madeinspace** [JakeHartnell/react-images-upload#21]
I'd love to use your module but using your example that's the error I get on compile, I'm using an app created by the create-react-app module so don't have control over the webpack configuration (I chose not to anyway):

./node_modules/react-images-upload/index.js
Module parse failed: Unexpected token (85:10)
You may need an appropriate loader to handle this file type.
|       renderIcon() {
|               if (this.props.withIcon) {
|                       return <div className="uploadIcon"/>;
|               }
|       }

**Comment by marianalucut7** [comment]
I get the same error on compile.

**Comment by joshuaai** [comment]
This is a known bug on create-react-app [#3856](https://github.com/facebook/create-react-app/issues/3856) with importing SVG files in CSS.

**Comment by IvanLinos** [comment]
Problem is not having a .svg file in the project, so i dont think the solution is converting it to inline code.
The problem that needs to be solved when adding this component to a project is that the parent project's bundler (webpack, parcel), needs to correctly handle jsx AND .css AND svg files.
What if the file was a .png instead a .svg? You couldn't inline it in the .css file, you would anyway need to tell the bundler how to handle the file, so this is the case.
I dont really see the benefict of chaning a svg file for its inline code inside the .css file, it is less handleable in my opinion.

**Comment by joshuaai** [comment]
I beg to differ. Every other file format works fine in my project. Please visit the CRA issue I referenced above.

**Comment by IvanLinos** [comment]
I think you have replied to yourself in the issue:

> "Webpack crashes in create-react-app when trying to parse `background: url(UploadIcon.svg)` as it cannot find a suitable loader."


So, you need to correctly configure webpack from the main project (create-react-app webpack config is NOT configured by default to handle .svg files) and add the correct loader to webpack's configuration:
```
{
    test: /\.svg$/,
    include: [/react-images-upload/],
    loader: 'file-loader',
    options: {
        name: '[name].[ext]?[hash]'
    }
}
```

I will probably add this to our Readme because i found myself figuring out this exact piece of code to make the .svg file be correctly handled by webpack in first app i added the component to.
So i think this is definitely the correct way to integrate the file, instead inlining it as code in the css file.

**Comment by joshuaai** [comment]
Hi @IvanLinos as you might already know, CRA does not provide the Webpack config files without ejecting.

Technically, the SVG file does not have to be imported in CSS. In this new PR #23 I followed the standard react approach and imported the SVG as a component, and using the `src` prop of the `<img />` tag to parse it. Everything works fine now.

**Comment by IvanLinos** [comment]
I pretty much consider this solution as a better aproach than having to set the webpack loader (im not a fan of webpack anyway :D).
Ill test it when i have time and if its ok for me and for @JakeHartnell i could merge your PR.

**Comment by sambit-gwl** [comment]
Is this bug fix is updated in npm [https://www.npmjs.com/package/react-images-upload](https://www.npmjs.com/package/react-images-upload)

**Comment by lodi-g** [comment]
Couldn't get it to work, even with the loader. :(

**Comment by SanderVanCamp** [comment]
Any updates on this issue? I'm on the 1.0.7 version but issue still persists. Thank you!

**Comment by SanderVanCamp** [comment]
@karanmartian, I managed to fix the problem. When using version 1.0.7 the issue is fixed. However, for some reason the code was not updated. U had to manually copy the code to my project and now it works.

**Comment by karanmartian** [comment]
@SanderVanCamp i had just installed 1.0.7 like 30 mins ago and then uninstalled it because of this issue. Can you make a new release if this is fixed. because in 1.0.7 its still not working.

**Comment by donalmurtagh** [comment]
I also have this problem in the latest version (1.0.7). The error message is:
```
Failed to compile.

./node_modules/react-images-upload/index.js
Module parse failed: Unexpected token (86:10)
You may need an appropriate loader to handle this file type.
|       renderIcon() {
|               if (this.props.withIcon) {
|                       return <img src={UploadIcon} className="uploadIcon" 
|                               alt="Upload Icon" />;
|               }
```

Presumably, the problem is using `UploadIcon` (an SVG) as the value of an image's `src` attribute.
I tried adding SVG files to the list of files processed by Webpack's url-loader
```
          {
            // I added SVG to this array
            test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/, /\.svg$/],
            loader: require.resolve('url-loader'),
            options: {
              limit: 10000,
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
```

But I still get the same error.

**Comment by donalmurtagh** [comment]
The reason for this error (and others), is that the source files, rather than the bundled files are being distributed. 

For example, rather than distributing a `.js` file, an `.svg` file, and a `.css` file, a single .js should be distributed with the .svg and .css file bundled within it.

While it might be possible for users to do this bundling within their own webpack config, they shouldn't have to.

**Comment by JakeHartnell** [comment]
> The reason for this error (and others), is that source files, rather than bundled files are being distributed.

Yes, this is the heart of it, and why @SanderVanCamp was able to get it working by manually copying the code into her project (where it would be bundled as part of create react app for example).

The solution is to ship a bundled distribution with the npm package. I've been meaning to do this for a while but have been swamped with work from other projects.

**Comment by JakeHartnell** [comment]
Ok, v1.0.8 is now published, and the pull request #29 is out for review. Try it an let me know if this is resolved.

https://www.npmjs.com/package/react-images-upload

**Comment by donalmurtagh** [comment]
@JakeHartnell v1.0.8 seems to be totally broken, I've left some further details [on the PR](https://github.com/JakeHartnell/react-images-upload/pull/29)

**Comment by JakeHartnell** [comment]
Should work now as of v1.0.95.

**Comment by LaKorita** [comment]
Hey guys, is this issue fixed? I'm using v1.0.99 and I see the following error: 

```ERROR in ./node_modules/react-images-upload/index.css
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .fileUploader {
|       width: 100%;
| }
 @ ./node_modules/react-images-upload/compiled.js 17:0-22
 @ ./src/scenes/AddActivity/index.js
 @ ./src/scenes/Application/Router.js
 @ ./src/scenes/Application/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server babel-polyfill ./src/index.js ```

**Comment by donalmurtagh** [comment]
@LaKorita it work fine for me in version 1.1.99. I suspect the reason you're having this problem is because you're importing the wrong file. In my case, I'm using ES6 imports
```
import ImageUploader from 'react-images-upload';
```

and this imports `compiled.js`

**Comment by songyanho** [comment]
Hi,

Although the file-loader managed to generate the URL but the SVG does not export properly.

<img width="906" alt="screen shot 2018-06-07 at 6 01 31 pm" src="https://user-images.githubusercontent.com/6477789/41093030-dbd21200-6a7c-11e8-892f-50981414e230.png">

**Comment by songyanho** [comment]
Just found a solution by adding css rule:
```
img.uploadIcon {
  content:url('./upload.svg') !important;
}
```
and attach your own svg/image.
